name: CMake

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-24.04]
        compiler: [gcc, clang]
        sqlite: [ON, OFF]
        system_sqlite: [ON, OFF]

    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout repository and submodules
      uses: actions/checkout@v3
      with:
        submodules: true

    - name: Update repository
      run: sudo apt update

    - name: Install dependencies
      run: |
        sudo apt install -y cmake
        if [ "${{ matrix.sqlite }}" == "ON" ]; then sudo apt install -y libsqlite3-dev; fi

    - name: Configure CMake
      run: |
        cmake -B ${{ github.workspace }}/build \
              -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }} \
              -DCMAKE_C_COMPILER=/usr/bin/${{ matrix.compiler }} \
              -DCMAKE_CXX_COMPILER=/usr/bin/${{ matrix.compiler }}++ \
              -DENABLE_SQLITE=${{ matrix.sqlite }} \
              -DWITH_SYSTEM_SQLITE=${{ matrix.system_sqlite }}

    - name: Build
      run: cmake --build ${{ github.workspace }}/build --config ${{ env.BUILD_TYPE }}